spring:
  profiles:
    active: dev
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinecourse?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  type-aliases-package: com.ning.adminmanage.model
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true

#公共api,url映射参数
api-url: /api
serverimgurl: http://192.168.243.129:88/ning/

server:
  port: 8088
#########################################################
#fastDFS
#
##############################################################
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 80
    height: 80
  tracker-list: 192.168.243.129:22122